### PR TITLE
update authkit urls

### PR DESCRIPTION
**Pull request by cosn**
These feel useful to have access to so you don't have to go to `@workos-inc/node`:

- Expose the `returnPathname`
- Expose `getAuthorizationUrl`

### CODE REVIEW

**Comment by PaulAsjes** [comment]
Hi there, could you explain why you need `getAuthorizationUrl` to be exposed? Is there something missing from `getSignUpUrl` and `getSignInUrl`?

**Comment by cosn** [comment]
technically with the first change, I don't. But philosophically, I think the ideal state would be that I only reference `authkit-remix`, and can get access to the underlying `workos/node` client for more complex stuff, I find it a bit odd that I have to use both, in different situations:
- have loader abstraction to make it easy
- have callback abstraction to make it easy
- expose a `client` which is the underlying workOS client, so I can call APIs on it subsequently 

All that said, totally fine to just have the URL changes and not the latter if you'd prefer

**Comment by PaulAsjes** [comment]
On exposing the Node SDK here, we're planning on consolidating all our JS libraries into one monorepo, which will make that part easy. I'm a little hesitant to expose the underlying client right now since it would likely require a breaking change in the future.

For the moment would you mind removing the `getAuthorizationUrl` part? Will happily approve afterward.

**Comment by cosn** [comment]
sounds good, ✅

**Comment by cosn** [comment]
sounds good, ✅

**Review by PaulAsjes — APPROVED** [review]

**Comment by cosn** [comment]
yep, signed

**Pull request merged**
